### PR TITLE
Added the Game-Playing functionality to the app

### LINKED ISSUE #11: Add logic for Game page
<h1>Can only be done after calculate winner function is made in helper.js file</h1>

**Please describe the feature you want this project to offer**
Add Logic for Game Page

**Describe the solution you'd like**
The game page should have various states like declaring the turn and calculating winners.

### PR DESCRIPTION
**Pull request by cyberquill**
# Story Title

[Add logic for Game page](https://github.com/username/repository-name/issues/11)

## Changes made

* Implemented the logic to allow two players to alternately play the game, one at a time.
* Race conditions handled.
* Stalemate Handled.
* Winner is displayed appropriately.
* Attempt to play the game after winning is blocked.

## How does the solution address the problem

tic-tac-toe

## Linked issues

Resolves #11 , also aids the development of #7 and #9

### CODE REVIEW

**Comment by cyberquill** [comment]
@r-ush another one from me, with love : )

**Comment by sloorush** [comment]
Looks Cool! I'll review it.

**Review by sloorush — CHANGES_REQUESTED** [review]
### Changes requested

- Please add package-lock.json to .gitignore
- Display which players turn it is on /game page
- add a button to route to "/game" on "/" route
- remove SCSS library since SCSS isn't utilized in the project

I request you to make these minor changes before I merge your or. Otherwise great work! @brij1999

**Comment by cyberquill** [comment]
@r-ush I have done the changes, please have a look.

**Comment by cyberquill** [comment]
@r-ush should I style it too in a separate PR?Or is someone already doing it?😅

**Review by sloorush — APPROVED** [review]

**Comment by sloorush** [comment]
Great Work @brij1999 ! Merging your PR

**Comment by sloorush** [comment]
We'll make a separate issue for the styling, you can take that up after that!

**Pull request merged**
